### ISSUE TITLE
cp errors

### ISSUE THREAD

**Issue by djpanda** [FezVrasta/ark-server-tools#758]
arkmanager --version 
Version: 1.6
Channel: master
Commit: aa6291c
Release Tag: v1.6.21
Blob SHA: d86fb71f33a2ffb247f8c4384435ebd4ffcebbcd

arkmanager update --update-mods give me some errors.

Copying files to /home/steam/ARK-Staging/Mods/764755314
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content/WallDoor/diag/CKF_StoneDoorwayDiag_sc.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content/WallDoor/diag/CKF_StoneDoorwayDiag_sc.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Lancets/Double/Diag/CKF_DoubleLanDiag_sc.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Lancets/Double/Diag/CKF_DoubleLanDiag_sc.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Lancets/Double/Diag/Wall_KeepDoubleLanDiag.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Lancets/Double/Diag/Wall_KeepDoubleLanDiag.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Lancets/Double/Wall_DoubleLancet.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Lancets/Double/Wall_DoubleLancet.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Lancets/DoubleTall/Diag/Wall_KeepDoubleTallLanDiag.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Lancets/DoubleTall/Diag/Wall_KeepDoubleTallLanDiag.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Lancets/DoubleTall/Diag/CKF_DoubleTallLanDiag_sc.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Lancets/DoubleTall/Diag/CKF_DoubleTallLanDiag_sc.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Lancets/DoubleTall/Wall_DoubleTallLancet.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Lancets/DoubleTall/Wall_DoubleTallLancet.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Lancets/TallSingle/Diag/CKF_SingleTallLanDiag_sc.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Lancets/TallSingle/Diag/CKF_SingleTallLanDiag_sc.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Lancets/TallSingle/Diag/Wall_KeepSingleTallLanDiag.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Lancets/TallSingle/Diag/Wall_KeepSingleTallLanDiag.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Lancets/TallSingle/Wall_SingleTallLancet.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Lancets/TallSingle/Wall_SingleTallLancet.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Lancets/Single/Diagonal/Wall_KeepSingleLanDiag.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Lancets/Single/Diagonal/Wall_KeepSingleLanDiag.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Lancets/Single/Diagonal/CKF_SingleLanDiag_sc.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Lancets/Single/Diagonal/CKF_SingleLanDiag_sc.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Lancets/Single/Wall_SingleLancet.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Lancets/Single/Wall_SingleLancet.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Lancets/TripleTall/Diag/Wall_KeepTripleTallLanDiag.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Lancets/TripleTall/Diag/Wall_KeepTripleTallLanDiag.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Lancets/TripleTall/Diag/CKF_TripleTallLanDiag_sc.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Lancets/TripleTall/Diag/CKF_TripleTallLanDiag_sc.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Lancets/TripleTall/Wall_TripleTallLancet.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Lancets/TripleTall/Wall_TripleTallLancet.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Lancets/Triple/Diag/Wall_KeepTripleLanDiag.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Lancets/Triple/Diag/Wall_KeepTripleLanDiag.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Lancets/Triple/Diag/CKF_TripleLanDiag_sc.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Lancets/Triple/Diag/CKF_TripleLanDiag_sc.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Lancets/Triple/Wall_TripleLancet.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Lancets/Triple/Wall_TripleLancet.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content3/Ornate/Half/KeepOrnateArchWalled.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content3/Ornate/Half/KeepOrnateArchWalled.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./2908/roundeddoorway/CKF_RoundedDoor_sc.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./2908/roundeddoorway/CKF_RoundedDoor_sc.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content2/cathredralWindow/Cathedralglass.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content2/cathredralWindow/Cathedralglass.uasset': Invalid cross-device link
cp: cannot create hard link '/srv/steam/ragnarok/ShooterGame/Content/Mods/764755314/./Content2/baywindow/Walltudorwindow_Keep.uasset' to '/home/steam/ARK-Staging/Mods/764755314/./Content2/baywindow/Walltudorwindow_Keep.uasset': Invalid cross-device link

**Comment by klightspeed** [comment]
This suggests your staging directory is on a separate filesystem to your server directory.

v1.6.22 should fix this.

**Comment by djpanda** [comment]
Thx yes i found the solution for myself. Changed your -al to -as option. Only wanted to let you know there is a problem on systems with /home on another partition :) But now i check if the update will fix it to. i prefer to not change code everytime i update the tools 👍

**Comment by djpanda** [comment]
rm: cannot remove '/home/steam/ARK-Staging/Binaries/Linux/*.txt': No such file or directory
is the only error still there after update to 1.6.22

my folder are at 
/home/steam/ARK-Staging/ShooterGame/Binaries/Linux

Dont know if its a problem with the script or maybe i did anything wrong but as i know the only place are the config where the Staging directory are set .

**Comment by djpanda** [comment]
StagingDir="/home/steam/ARK-Staging"  are set in the arkmanager.cfg

**Comment by klightspeed** [comment]
> ```
rm: cannot remove '/home/steam/ARK-Staging/Binaries/Linux/*.txt': No such file or directory
```
> is the only error still there after update to 1.6.22

Just means the script needs to check if any such files exist before trying to remove them.

**Comment by djpanda** [comment]
Yes but it looks like in it is searching in the wrong place, or ? my path have "ShooterGame/" in the middle

**Comment by klightspeed** [comment]
9f188a5 should fix this.

**Comment by djpanda** [comment]
fast reaction :) thx
